ALERTE_WILDFIRE:
  Nvseismolab_set1:
    label: pyronear_v0
    ratio: [1, 0.02]
    subset: ["pyronear_v0_smoke.txt",  "pyronear_v0_no_smoke.txt"]
  fp:
    label: pyronear_v0
    ratio: 1
    subset: null
    dt: 1500
  pyronear:
    label: pyronear_v0
    ratio: 1
    subset: null
HPWREN:
  AiForManKind_cloud:
    label: pyronear_v0
    ratio: 0.001
    subset: null
  AiForManKind_fog:
    label: pyronear_v0
    ratio: 0.01
    subset: null
  AiForManKind_sunrise:
    label: pyronear_v0
    ratio: 0.01
    subset: null
  AiForManKind_v1:
    label: pyronear_v0
    ratio: 1
    subset: null
  AiForManKind_v2:
    label: pyronear_v0
    ratio: 1
    subset: null
  Fuego:
    label: pyronear_v0
    ratio: 0.5
    subset: null
PYRONEAR:
  ardeche_set0:
    label: pyronear_v0
    ratio: 0.1
    subset: "false_positive.txt"
  gironde_set0:
    label: pyronear_v0
    ratio: 0
    subset: null
  fp:
    label: pyronear_v0
    ratio: 0.5
    subset: null
    dt: 1500
  fp_adf:
    label: pyronear_v0
    ratio: 1
    subset: null
    dt: 120
  wildfires:
    label: pyronear_v0
    ratio: 1.0
    subset: null
  adf:
    label: pyronear_v0
    ratio: 1
    subset: null
UNKNOWN:
  fog_clouds:
    label: pyronear_v0
    ratio: 0.1
    subset: null
  smoke:
    label: pyronear_v0
    ratio: 1.0
    subset: null
